//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPostgre.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ferias
    {
        public int id { get; set; }
        public Nullable<int> id_pretensoes { get; set; }
        public Nullable<System.DateTime> per1_inicio { get; set; }
        public Nullable<System.DateTime> per1_fim { get; set; }
        public Nullable<System.DateTime> per2_inicio { get; set; }
        public Nullable<System.DateTime> per2_fim { get; set; }
        public Nullable<bool> ativo { get; set; }
        public string alterado { get; set; }
        public System.DateTime cadastro { get; set; }
        public string situacao { get; set; }
        public string observacoes { get; set; }
        public string status { get; set; }
    
        public virtual Pretensao pretensoes { get; set; }
    }
}
