//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPostgre
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CallcenterEntities : DbContext
    {
        public CallcenterEntities()
            : base("name=CallcenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cargos> cargos { get; set; }
        public virtual DbSet<divfuncionario> divfuncionario { get; set; }
        public virtual DbSet<Divisao> divisoes { get; set; }
        public virtual DbSet<ferias> ferias { get; set; }
        public virtual DbSet<funcionarios> funcionarios { get; set; }
        public virtual DbSet<pretensoes> pretensoes { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<vagas> vagas { get; set; }
    }
}
