//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPostgre
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public funcionarios()
        {
            this.divfuncionario = new HashSet<divfuncionario>();
            this.divfuncionario1 = new HashSet<divfuncionario>();
            this.usuarios = new HashSet<usuarios>();
        }
    
        public int id { get; set; }
        public Nullable<int> registro { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> nascimento { get; set; }
        public Nullable<System.DateTime> per_aquisitivo { get; set; }
        public string endereco { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string cidade { get; set; }
        public string bairro { get; set; }
        public string cep { get; set; }
        public string telefone1 { get; set; }
        public string telefone2 { get; set; }
        public string telefone3 { get; set; }
        public Nullable<int> id_cargo { get; set; }
        public Nullable<System.DateTime> cadastro { get; set; }
        public string alterado { get; set; }
        public Nullable<bool> ativo { get; set; }
    
        public virtual cargos cargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<divfuncionario> divfuncionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<divfuncionario> divfuncionario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarios> usuarios { get; set; }
    }
}
