//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPostgre
{
    using System;
    using System.Collections.Generic;
    
    public partial class pretensoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pretensoes()
        {
            this.ferias = new HashSet<ferias>();
        }
    
        public int id { get; set; }
        public int id_divfuncionarios { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<System.DateTime> per1_op1_inicio { get; set; }
        public Nullable<System.DateTime> per1_op1_fim { get; set; }
        public Nullable<System.DateTime> per1_op2_inicio { get; set; }
        public Nullable<System.DateTime> per1_op2_fim { get; set; }
        public Nullable<System.DateTime> per1_op3_inicio { get; set; }
        public Nullable<System.DateTime> per1_op3_fim { get; set; }
        public Nullable<System.DateTime> per2_op1_inicio { get; set; }
        public Nullable<System.DateTime> per2_op1_fim { get; set; }
        public Nullable<System.DateTime> per2_op2_inicio { get; set; }
        public Nullable<System.DateTime> per2_op2_fim { get; set; }
        public Nullable<System.DateTime> per2_op3_inicio { get; set; }
        public Nullable<System.DateTime> per2_op3_fim { get; set; }
        public Nullable<bool> ativo { get; set; }
        public string alterado { get; set; }
        public System.DateTime cadastro { get; set; }
    
        public virtual divfuncionario divfuncionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ferias> ferias { get; set; }
    }
}
