//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPostgre
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id_funcionario { get; set; }
        public string senha { get; set; }
        public Nullable<bool> ativo { get; set; }
        public string alterado { get; set; }
        public System.DateTime cadastro { get; set; }
        public string perfil { get; set; }
        public int id { get; set; }
    
        public virtual Funcionario funcionarios { get; set; }
    }
}
