//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPostgre
{
    using System;
    using System.Collections.Generic;
    
    public partial class vagas
    {
        public int id { get; set; }
        public Nullable<int> mes { get; set; }
        public Nullable<int> ano { get; set; }
        public string turno { get; set; }
        public Nullable<int> id_cargo { get; set; }
    
        public virtual cargos cargos { get; set; }
    }
}
